import type { CurriculumTemplateMap } from "./types";

export const curriculumTemplates: CurriculumTemplateMap = {
    JuniorHigh: {
        J1: {
            "数学": {
                source: "学習指導要領準拠",
                units: [
                    { name: "正負の数", estimatedSessions: 5, weight: 14, confidence: "high" },
                    { name: "文字と式", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "一次方程式", estimatedSessions: 5, weight: 14, confidence: "high" },
                    { name: "比例と反比例", estimatedSessions: 5, weight: 14, confidence: "high" },
                    { name: "平面図形", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "空間図形", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "データの活用", estimatedSessions: 3, weight: 8, confidence: "medium" },
                ],
            },
            "英語": {
                source: "学習指導要領準拠",
                units: [
                    { name: "be動詞", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "一般動詞", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "名詞・代名詞の複数形", estimatedSessions: 2, weight: 8, confidence: "high" },
                    { name: "疑問詞", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "三人称単数現在", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "現在進行形", estimatedSessions: 2, weight: 8, confidence: "high" },
                    { name: "一般動詞の過去形", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "canの文", estimatedSessions: 2, weight: 7, confidence: "high" },
                    { name: "命令文", estimatedSessions: 2, weight: 7, confidence: "medium" },
                ],
            },
            "国語": {
                source: "学習指導要領準拠",
                units: [
                    { name: "漢字・語彙（中1）", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "文法（文の成分・品詞）", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "説明的文章の読解", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "文学的文章の読解", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "古典入門（歴史的仮名遣い）", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "作文・表現", estimatedSessions: 3, weight: 10, confidence: "medium" },
                    { name: "詩・短歌・俳句", estimatedSessions: 2, weight: 7, confidence: "medium" },
                ],
            },
            "理科": {
                source: "学習指導要領準拠",
                units: [
                    { name: "植物の体のつくりとはたらき", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "動物の分類", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "身のまわりの物質", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "気体の性質", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "水溶液の性質", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "光と音", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "力のはたらき", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "大地の変化", estimatedSessions: 3, weight: 10, confidence: "high" },
                ],
            },
            "社会": {
                source: "学習指導要領準拠",
                units: [
                    { name: "世界の姿", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "世界各地の人々の生活と環境", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "世界の諸地域", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "日本の姿", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "日本の諸地域", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "古代までの日本", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "中世の日本", estimatedSessions: 3, weight: 10, confidence: "high" },
                ],
            },
        },
        J2: {
            "数学": {
                source: "学習指導要領準拠",
                units: [
                    { name: "式の計算", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "連立方程式", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "一次関数", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "平行と合同", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "三角形と四角形", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "確率", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "データの比較", estimatedSessions: 3, weight: 8, confidence: "medium" },
                ],
            },
            "英語": {
                source: "学習指導要領準拠",
                units: [
                    { name: "be動詞の過去形", estimatedSessions: 2, weight: 8, confidence: "high" },
                    { name: "過去進行形", estimatedSessions: 2, weight: 8, confidence: "high" },
                    { name: "未来形 (will/be going to)", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "助動詞", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "不定詞", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "動名詞", estimatedSessions: 2, weight: 8, confidence: "high" },
                    { name: "比較級・最上級", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "受動態", estimatedSessions: 3, weight: 10, confidence: "medium" },
                    { name: "接続詞", estimatedSessions: 2, weight: 7, confidence: "medium" },
                ],
            },
            "国語": {
                source: "学習指導要領準拠",
                units: [
                    { name: "漢字・語彙（中2）", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "文法（用言の活用）", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "論説文の読解", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "小説の読解", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "古文の読解", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "漢文入門", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "意見文・小論文", estimatedSessions: 3, weight: 10, confidence: "medium" },
                ],
            },
            "理科": {
                source: "学習指導要領準拠",
                units: [
                    { name: "化学変化と原子・分子", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "化学変化と物質の質量", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "電流とその利用", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "電流と磁界", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "動物の体のつくりとはたらき", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "気象のしくみと天気の変化", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "日本の気象", estimatedSessions: 3, weight: 10, confidence: "high" },
                ],
            },
            "社会": {
                source: "学習指導要領準拠",
                units: [
                    { name: "近世の日本", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "近代の日本と世界", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "二度の世界大戦と日本", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "現代の日本と世界", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "日本の地域的特色", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "世界と比べた日本の地域的特色", estimatedSessions: 3, weight: 10, confidence: "medium" },
                ],
            },
        },
        J3: {
            "数学": {
                source: "学習指導要領準拠",
                units: [
                    { name: "多項式の展開と因数分解", estimatedSessions: 5, weight: 14, confidence: "high" },
                    { name: "平方根", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "二次方程式", estimatedSessions: 5, weight: 14, confidence: "high" },
                    { name: "関数 y=ax²", estimatedSessions: 5, weight: 14, confidence: "high" },
                    { name: "相似な図形", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "円の性質", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "三平方の定理", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "標本調査", estimatedSessions: 2, weight: 6, confidence: "medium" },
                ],
            },
            "英語": {
                source: "学習指導要領準拠",
                units: [
                    { name: "現在完了形", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "現在完了進行形", estimatedSessions: 2, weight: 8, confidence: "high" },
                    { name: "関係代名詞", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "間接疑問文", estimatedSessions: 2, weight: 8, confidence: "high" },
                    { name: "分詞の形容詞的用法", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "仮定法", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "長文読解演習", estimatedSessions: 5, weight: 15, confidence: "medium" },
                    { name: "英作文演習", estimatedSessions: 3, weight: 10, confidence: "medium" },
                ],
            },
            "国語": {
                source: "学習指導要領準拠",
                units: [
                    { name: "漢字・語彙（中3）", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "文法（助詞・助動詞）", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "論説文・評論文の読解", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "文学的文章の読解（中3）", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "古文の読解（中3）", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "漢文の読解", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "小論文・作文", estimatedSessions: 3, weight: 10, confidence: "medium" },
                ],
            },
            "理科": {
                source: "学習指導要領準拠",
                units: [
                    { name: "水溶液とイオン", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "化学変化と電池", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "運動とエネルギー", estimatedSessions: 5, weight: 15, confidence: "high" },
                    { name: "仕事とエネルギー", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "生命の連続性", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "遺伝の規則性", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "地球と宇宙", estimatedSessions: 4, weight: 12, confidence: "high" },
                    { name: "自然と人間", estimatedSessions: 2, weight: 7, confidence: "medium" },
                ],
            },
            "社会": {
                source: "学習指導要領準拠",
                units: [
                    { name: "現代社会と私たちの生活", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "個人の尊重と日本国憲法", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "民主政治と政治参加", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "市場経済と金融", estimatedSessions: 4, weight: 13, confidence: "high" },
                    { name: "財政と国民の福祉", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "国際社会と世界平和", estimatedSessions: 3, weight: 10, confidence: "high" },
                    { name: "私たちと国際社会の課題", estimatedSessions: 3, weight: 10, confidence: "medium" },
                ],
            },
        },
    },
    Elementary: {},
    HighSchool: {},
};
